version: 2
jobs:
  build:
    working_directory: ~/News-Feed
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx2g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "guardianapi/build.gradle"}}-{{ checksum "newsapi/build.gradle"}}-{{ checksum "cache/build.gradle"}}-{{ checksum "data/build.gradle"}}-{{ checksum  "domain/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "guardianapi/build.gradle"}}-{{ checksum "newsapi/build.gradle"}}-{{ checksum "cache/build.gradle"}}-{{ checksum "data/build.gradle"}}-{{ checksum  "domain/build.gradle" }}
      - run:
          name: Build Debug
          command: ./gradlew assembleDebug
      - run:
          name: Run KtlintFormat
          command: ./gradlew ktlintFormat
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-result
