version: 2
jobs:
  build:
    working_directory: ~/News-Feed
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx2g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}-{{ checksum "guardianapi/build.gradle.kts"}}-{{ checksum "newsapi/build.gradle.kts"}}
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}-{{ checksum "guardianapi/build.gradle.kts"}}-{{ checksum "newsapi/build.gradle.kts"}}
      - run:
          name: Build Debug
          command: ./gradlew assembleDebug
      - run:
          name: Run ktlint
          command: ./gradlew ktlint
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-result
